### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by vimto** [JavaScript-NZ/Society-Documentation#11]
E.g. http://www.meetup.com/WellingtonJS/pages/The_WellingtonJS_Code_of_Conduct

**Comment by Unfocused** [comment]
See also the agenda item for the upcoming AGM: https://github.com/JavaScript-NZ/Society-Meetings/issues/14

**Comment by Unfocused** [comment]
https://github.com/JavaScript-NZ/Society-Documentation/pull/14

**Comment by jenofdoom** [comment]
Closing this as it's a dupe of above mentioned issue
